const CONFIG = {
    titleWeb: "Gửi em",
    introTitle: 'Tình yêu của anh',
    introDesc: `Anh mong chúng ta hãy luôn luôn cùng nhau bước trên con đường khó khăn này`,
    btnIntro: '^^click^^',
    title: 'Chúng ta gặp nhau là duyên phận nên anh mong là Anh và Em sẽ luôn đồng hành cùng nhau dù khó khăn như thế nào đi nữa🥰',
    title: 'Anh mong dù là vui vẻ hay giận hờn thì chúng ta sẽ luôn cùng nhau vượt qua mọi chuyện nhé,🥰Anh Yêu Em🥰',
    desc: 'Thoát web là chấp nhận rồi nhé!!!',
    btnYes: 'Đồng Ý <33',
    btnNo: 'Không nha :3',
    question: 'Để lại một câu nói đi nek <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Anh yêu em nhiều lắm <33333333',
    mess: 'Anh biết mà 🥰. Anh biết em sẽ đồng ý mà 😘😘',
    messDesc: 'Hẹn em, Vào một ngày không xa nhé.',
    btnAccept: 'Okiiiii lun <3',
}
